### ISSUE TITLE
Date Flickers

### ISSUE THREAD

**Issue by kghunt** [kghunt/Basic_Watch#13]
After the recent update the date Flickers when the screen updates.

**Comment by uXeBoy** [comment]
This would be because you are updating the display _before_ printing the date here:

https://github.com/kghunt/Basic_Watch/blob/973fd10186faa05c4b5056118b1eaa7987af5eb2/Basic_Watch.ino#L363

...and then updating the display again _after_ printing the date?

**Comment by kghunt** [comment]
Brilliant. Well spotted! I will fix that ASAP.

**Comment by kghunt** [comment]
Fixed. Thanks @uXeBoy
